sudo: false

language: ruby

rvm:
  - 2.2.2

env:
  - DB=postgresql

before_script:
  - psql -c 'create database classroom_test;' -U postgres

script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test

bundler_args: --without development production --deployment --jobs=3 --retry=3
