language: ruby

sudo: false

rvm:
  - 2.2.3

env:
  - DB=postgresql

before_script:
  - psql -c 'create database classroom_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - ./script/test

bundler_args: --without development production --deployment --jobs=3 --retry=3
