language: ruby

rvm:
  - 2.4.1

node_js:
  - 7.7.1

sudo: false

before_install:
  - gem update --system
  - nvm install 7.7.1
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - psql -c 'create database classroom_test;' -U postgres
  - bundle exec rake db:schema:load

script:
  - ./script/cibuild

cache:
  bundler: true
  yarn: true

install:
  - bundle install --without development production --deployment --jobs=3 --retry=3
  - yarn install

services:
  - postgresql
  - redis-server

env:
  global:
    - GITHUB_CLIENT_ID=client_id
    - GITHUB_CLIENT_SECRET=client_secret
    - WEBHOOK_SECRET=abcdefg
    - CLASSROOM_WEBHOOK_URL_PREFIX="https://example.com/github/hooks"

notifications:
  email: false
