language: ruby

node_js:
  - 7

sudo: false

before_install:
  - gem update --system
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - psql -c 'create database classroom_test;' -U postgres
  - bundle exec rake db:schema:load
  - bundle exec rake factory_bot:lint

script:
  - "KNAPSACK_GENERATE_REPORT=true ./bin/rake knapsack:rspec"

cache:
  bundler: true
  yarn: true

install:
  - bundle install --local --without development production --deployment --jobs=3 --retry=3
  - yarn install

services:
  - postgresql
  - redis-server

env:
  global:
    - CI_NODE_TOTAL=2
    - CLASSROOM_WEBHOOK_URL_PREFIX="https://example.com/github/hooks"
    - GITHUB_CLIENT_ID=client_id
    - GITHUB_CLIENT_SECRET=client_secret
    - RAILS_ENV=test
    - RACK_ENV=test
    - REDIS_URL="redis://localhost:6379/0"
    - WEBHOOK_SECRET=abcdefg
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1

notifications:
  email: false
  slack:
    secure: hYvPi67Ka3T873Roo2WASv6anZUqnkkcvFjUrtxnYwDB14XueP9VXAbFFW8zYl9Uj6eAsPzxbGsGUzW0dUvhHXElffglNnrSh33FtbvrImnzhJvhORYh9+sFK1QWZEKj10oon715kjkRaltu2gqB0fon2bvGgFfdbLQJj8Kh6m8=
