# config/chewy.yml
# separate environment configs
test:
  host: 'localhost:9227'
  prefix: 'test'

development:
  host: 'localhost:9227'

production:
  host: <%= "#{ENV['FOUNDELASTICSEARCH_URL']}:9243" %>
