# For information on Sidekiq queues:
# https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues

---
:concurrency: <%= Integer(ENV['SIDEKIQ_CONCURRENCY'] || 5) %>
:verbose: false
:queues: # https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues
  - [assignment,   1]
  - [chewy,        1]
  - [last_active,  1]
  - [github_event, 3]
  - [trash_can,    2]
  - [deadline,     3]
  - [boom,         3]
